---
# tasks file for win_ad_install
- name: install windows active directory
  win_feature:
    name: AD-Domain-Services
    state: present

- name: set up AD controller
  win_domain:
    dns_domain_name: "{{ssh_host}}"
    safe_mode_password: "{{ansible_password}}"
  
- name: reboot after setting up AD controller
  win_reboot:

- name: list domain list after reboot
  dclist: "{{ ad_domain_name }}"