---
# tasks file for win_ad_install
- name: install windows active directory
  win_feature:
    name: AD-Domain-Services
    state: present

- name: set up AD controller
  win_domain:
    dns_domain_name: "{{ssh_host}}"
    safe_mode_password: "{{ansible_password}}"

- name: reboot machine  
  win_reboot:
    reboot_timeout: "1200"

- name: list domain list after reboot
  win_shell: nltest /dclist:{{ ad_domain_name }}
  register: output
  tags:
    - ready 

- name: show domain list
  debug:
    msg: "{{item}}"
  with_items: {{output}}
  tags:
    - ready
