---
# tasks file for win_service_config
- name: install chocolatey
  win_chocolatey:
    name: "chocolatey"
    state: downgrade
    version: 0.10.11

- name: install SSH
  win_chocolatey:
    name: "{{package_name}}"
    state: present
    params: "{{ parameters }}"
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: enable SSH service
  win_service:
    name: "{{service_name}}"
    state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Add win_firewall_rule
  win_firewall_rule:
    name: "{{service_name}}"
    localport: "{{local_port}}"
    action: allow
    direction: in
    protocol: "{{protocol_name}}"
    state: present
    enabled: yes